on: 
  push:
    branches: "main"

jobs:
  # job id, can be anything
  export:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: "Install Godot"
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.1.1
    - name: "Export Godot project"
      run: godot --headless --export-pack "Hathora Server" ./server.pck
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Hathora CLI
      run: "npm install -g @hathora/cli"
    - name: Hathora Deploy
      id: deploy
      run: "./hathora-deploy.sh ${{ secrets.HATHORA_TOKEN }}"
